### ISSUE TITLE
Spells

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/SuperTome-old-latex#22]
The spell entries have to be added. Not quite looking forward to that one.

**Comment by Aktariel** [comment]
The good news is that most of this work has been done already - there should be a spell class and the vast majority of OGL spells have been formatted already. I don't think I have commit access to this repor, but the files should be able to be pulled from the archived AwesomeTome repo.

**Comment by Lokathor** [comment]
I've been looking into using GitBook as a platform, since it's more mobile friendly, and people usually have phones during gameplay but not always actual laptops https://lokathor.gitbooks.io/supertome/content/

**Comment by Aktariel** [comment]
Interesting. Are you considering converting the whole thing to Markdown?

Also, I found the spells - the 760K spells.tex in the 07Source and TypeTest branches, is the file that has the OGL spells that TarkisFlux imported at some point. No spell class, though, so there's a lot of extraneous formatting.

**Comment by Lokathor** [comment]
Yeah. Initial "how to play" stuff that isn't quite written up how I want I'm writing by hand as a way to also make sure that everything is "tome-ified" where possible. Once I get to a lot of "mindless bulk" work like spell entries I think I'll work up a LaTeX to GitMarkdown converter system.
